Enable legacy DRI1 drivers.
Because the error below on build Parallels.
/usr/src/parallels/kmods/prl_vid/Video/Guest/Linux/kmod/prldrm.c:2531:3: error: 'struct drm_driver' has no member named 'irq_handler'